# Site Settings
title: Joshua Koh
email: joshua@kohfamily.com
description: Joshua's personal space for crazy ideas and adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.joshuakoh.me" # the base hostname & protocol for your site
date_format: "%b %-d, %Y"

# User Settings
username: Joshua Koh
user_description: Data scientist in training at Georgia Tech and daily flesh fighter. ESTJ with feelings, gamer with rhythm, water with lemon.
disqus_username: koh4theking

# Social Media
# Remove the item if you don't need it
github_username: joshuakoh
twitter_username: jkoh33
linkedin_username: joshuatkoh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: What is Koh-reative?
    url: /koh-reative/
  - title: Koh-reative Archive
    url: /koh-reative/archive/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
