# Site Settings
title: Josh's Website
email: joshua@kohfamily.com
description: Joshua's crazy ideas and adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.joshuakoh.me" # the base hostname & protocol for your site
date_format: "%b %-d, %Y"

# User Settings
username: Joshua Koh
user_description: Making sunny days out of Clouds and fighting my flesh daily. My best friends are pianos, board games, books, and Charissa.
disqus_username: koh4theking

# Social Media
# Remove the item if you don't need it
twitter_username: koh4theking
linkedin_username: joshuatkoh
github_username: joshuakoh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: What is Koh-reative?
    url: /koh-reative/
  - title: Koh-reative Archive
    url: /koh-reative/archive/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
